import { Listing } from "./types";
import propertyHouse2bed from "@/assets/property-house-2bed.jpg";
import propertyRoom from "@/assets/property-room.jpg";
import propertyHouse3bed from "@/assets/property-house-3bed.jpg";
import propertyBedsitter from "@/assets/property-bedsitter.jpg";
import propertyShop from "@/assets/property-shop.jpg";
import propertyApartment from "@/assets/property-apartment.jpg";
import propertyHouse4bed from "@/assets/property-house-4bed.jpg";
import propertyOffice from "@/assets/property-office.jpg";

export const sampleListings: Listing[] = [
  {
    id: "1",
    title: "Spacious 2 Bedroom in Area 47",
    propertyType: "House",
    bedrooms: 2,
    rentPrice: 150000,
    city: "Lilongwe",
    area: "Area 47",
    description: "A well-maintained 2-bedroom house in the heart of Area 47. Close to shops, schools, and public transport. Spacious living room and a nice backyard. Ideal for a small family or working professionals.",
    amenities: ["Water", "Electricity", "Flush Toilet", "Bathroom", "Kitchen", "Parking"],
    images: [propertyHouse2bed],
    contactPhone: "+265888123456",
    contactWhatsapp: "+265888123456",
    status: "Available",
    isApproved: true,
    isFeatured: true,
    viewCount: 234,
    createdAt: "2026-03-10",
    landlordName: "James Banda",
    lat: -13.9526, lng: 33.7541,
  },
  {
    id: "2",
    title: "Single Room in Namiwawa",
    propertyType: "Room",
    bedrooms: 1,
    rentPrice: 35000,
    city: "Lilongwe",
    area: "Namiwawa",
    description: "Affordable single room for students or single working professionals. Shared bathroom and kitchen. Very close to Queen Elizabeth Central Hospital and the city centre.",
    amenities: ["Electricity", "Water", "Pit Toilet", "Bathroom"],
    images: [propertyRoom],
    contactPhone: "+265999234567",
    contactWhatsapp: "+265999234567",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 89,
    createdAt: "2026-03-12",
    landlordName: "Grace Phiri",
    lat: -15.7867, lng: 35.0068,
  },
  {
    id: "3",
    title: "3 Bedroom House in Area 43",
    propertyType: "House",
    bedrooms: 3,
    rentPrice: 250000,
    city: "Lilongwe",
    area: "Area 43",
    description: "Beautiful 3-bedroom house with modern finishes in Area 43. Tiled floors throughout, large kitchen, and a secure compound with a wall fence. Perfect for families.",
    amenities: ["Water", "Electricity", "Flush Toilet", "Bathroom", "Kitchen", "Parking", "Wall Fence", "Tiled Floors"],
    images: [propertyHouse3bed],
    contactPhone: "+265884345678",
    contactWhatsapp: "+265884345678",
    status: "Available",
    isApproved: true,
    isFeatured: true,
    viewCount: 412,
    createdAt: "2026-03-08",
    landlordName: "Patrick Moyo",
    lat: -13.9726, lng: 33.7841,
  },
  {
    id: "4",
    title: "Bedsitter near Bunda Turnoff",
    propertyType: "Bedsitter",
    bedrooms: 1,
    rentPrice: 80000,
    city: "Lilongwe",
    area: "Bunda Turnoff",
    description: "Self-contained bedsitter with its own bathroom and small kitchenette. Good for LUANAR students or single professionals. Located near Bunda Turnoff with easy access to the city.",
    amenities: ["Water", "Electricity", "Flush Toilet", "Bathroom", "Kitchen"],
    images: [propertyBedsitter],
    contactPhone: "+265991456789",
    contactWhatsapp: "+265991456789",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 156,
    createdAt: "2026-03-14",
    landlordName: "Mercy Chirwa",
    lat: -13.9826, lng: 33.7641,
  },
  {
    id: "5",
    title: "Shop Space in Limbe Market",
    propertyType: "Shop/Office",
    bedrooms: 0,
    rentPrice: 100000,
    city: "Zomba",
    area: "Limbe",
    description: "Prime shop space in Limbe Market area. High foot traffic, perfect for retail business. Includes electricity and water. Ground floor with good visibility from the main road.",
    amenities: ["Electricity", "Water"],
    images: [propertyShop],
    contactPhone: "+265888567890",
    contactWhatsapp: "+265888567890",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 78,
    createdAt: "2026-03-11",
    landlordName: "Charles Kamanga",
    lat: -15.8167, lng: 35.0568,
  },
  {
    id: "6",
    title: "Modern 2 Bedroom Apartment in Mapanga",
    propertyType: "Apartment",
    bedrooms: 2,
    rentPrice: 180000,
    city: "Zomba",
    area: "Mapanga",
    description: "Newly built 2-bedroom apartment in a quiet area of Mapanga. Modern kitchen, tiled floors, and ample parking. Security guard on site 24/7.",
    amenities: ["Water", "Electricity", "Flush Toilet", "Bathroom", "Kitchen", "Parking", "Tiled Floors"],
    images: [propertyApartment],
    contactPhone: "+265995678901",
    contactWhatsapp: "+265995678901",
    status: "Available",
    isApproved: true,
    isFeatured: true,
    viewCount: 321,
    createdAt: "2026-03-09",
    landlordName: "Agnes Nkhoma",
    lat: -15.7467, lng: 35.0368,
  },
  {
    id: "7",
    title: "Student Room near UNIMA Zomba",
    propertyType: "Room",
    bedrooms: 1,
    rentPrice: 30000,
    city: "Zomba",
    area: "University Area",
    description: "Cozy room near UNIMA Zomba campus. Walking distance to Chancellor College. Shared bathroom. Quiet neighbourhood good for studying. Includes water and electricity.",
    amenities: ["Water", "Electricity", "Pit Toilet", "Bathroom"],
    images: [propertyRoom],
    contactPhone: "+265881789012",
    contactWhatsapp: "+265881789012",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 67,
    createdAt: "2026-03-13",
    landlordName: "Blessings Nyirenda",
    lat: -15.3833, lng: 35.3188,
  },
  {
    id: "8",
    title: "4 Bedroom House in Area 25",
    propertyType: "House",
    bedrooms: 4,
    rentPrice: 350000,
    city: "Lilongwe",
    area: "Area 25",
    description: "Spacious 4-bedroom house in Area 25 with a large garden, servant quarters, and double garage. High-end finishes throughout. Ideal for diplomats or large families.",
    amenities: ["Water", "Electricity", "Flush Toilet", "Bathroom", "Kitchen", "Parking", "Wall Fence", "Tiled Floors"],
    images: [propertyHouse4bed],
    contactPhone: "+265999890123",
    contactWhatsapp: "+265999890123",
    status: "Available",
    isApproved: true,
    isFeatured: true,
    viewCount: 567,
    createdAt: "2026-03-07",
    landlordName: "Dr. Kondwani Msiska",
    lat: -13.9426, lng: 33.8041,
  },
  {
    id: "9",
    title: "Student Room near Chancellor College",
    propertyType: "Room",
    bedrooms: 1,
    rentPrice: 25000,
    city: "Zomba",
    area: "Chancellor College",
    description: "Affordable room for Chancellor College (UNIMA) students. Just 5 minutes walk from campus. Shared facilities. Quiet study environment. Many students in the area.",
    amenities: ["Electricity", "Water", "Pit Toilet"],
    images: [propertyRoom],
    contactPhone: "+265884901234",
    contactWhatsapp: "+265884901234",
    status: "Available",
    isApproved: true,
    isFeatured: true,
    viewCount: 245,
    createdAt: "2026-03-15",
    landlordName: "Martha Gondwe",
    lat: -15.3933, lng: 35.3288,
  },
  {
    id: "10",
    title: "Office Space in City Centre",
    propertyType: "Shop/Office",
    bedrooms: 0,
    rentPrice: 200000,
    city: "Lilongwe",
    area: "City Centre",
    description: "Professional office space in Lilongwe City Centre. 3 rooms with reception area. Air conditioned. Suitable for NGOs, consultancy firms, or business offices.",
    amenities: ["Electricity", "Water", "Flush Toilet", "Parking"],
    images: [propertyOffice],
    contactPhone: "+265991012345",
    contactWhatsapp: "+265991012345",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 203,
    createdAt: "2026-03-06",
    landlordName: "Robert Chilima",
    lat: -13.9626, lng: 33.7741,
  },
  {
    id: "11",
    title: "2 Bedroom in Chirimba, Zomba",
    propertyType: "House",
    bedrooms: 2,
    rentPrice: 120000,
    city: "Zomba",
    area: "Chirimba",
    description: "Neat 2-bedroom house in Chirimba. Recently renovated with new plumbing and electrical. Close to shops and public transport. Good for small families.",
    amenities: ["Water", "Electricity", "Flush Toilet", "Bathroom", "Kitchen", "Wall Fence"],
    images: [propertyHouse2bed],
    contactPhone: "+265888112233",
    contactWhatsapp: "+265888112233",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 189,
    createdAt: "2026-03-11",
    landlordName: "Esther Mwale",
    lat: -15.3633, lng: 35.2988,
  },
  {
    id: "12",
    title: "Bedsitter in Area 18, Lilongwe",
    propertyType: "Bedsitter",
    bedrooms: 1,
    rentPrice: 65000,
    city: "Lilongwe",
    area: "Area 18",
    description: "Compact self-contained bedsitter in Area 18. Includes bathroom and cooking space. Ideal for single working professionals or UNIMA students. Close to Old Town.",
    amenities: ["Water", "Electricity", "Flush Toilet", "Bathroom", "Kitchen"],
    images: [propertyBedsitter],
    contactPhone: "+265995223344",
    contactWhatsapp: "+265995223344",
    status: "Taken",
    isApproved: true,
    isFeatured: false,
    viewCount: 98,
    createdAt: "2026-03-05",
    landlordName: "Felix Kumwenda",
    lat: -13.9326, lng: 33.7841,
  },
  {
    id: "13",
    title: "Affordable Room in Dzaleka Camp",
    propertyType: "Room",
    bedrooms: 1,
    rentPrice: 20000,
    city: "Dzaleka",
    area: "Dzaleka Main",
    description: "Simple but clean room available in Dzaleka Refugee Camp. Close to market and community centre. Water and electricity included. Ideal for individuals or couples.",
    amenities: ["Water", "Electricity", "Pit Toilet"],
    images: [propertyRoom],
    contactPhone: "+265881334455",
    contactWhatsapp: "+265881334455",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 134,
    createdAt: "2026-03-16",
    landlordName: "Emmanuel Habimana",
    lat: -13.7833, lng: 33.9833,
  },
  {
    id: "14",
    title: "2 Bedroom House in Dzaleka",
    propertyType: "House",
    bedrooms: 2,
    rentPrice: 45000,
    city: "Dzaleka",
    area: "Dzaleka Extension",
    description: "Newly built 2-bedroom house in Dzaleka extension area. Has a small compound. Water from borehole. Electricity connected. Good for small families.",
    amenities: ["Water", "Electricity", "Pit Toilet", "Bathroom", "Kitchen"],
    images: [propertyHouse2bed],
    contactPhone: "+265999445566",
    contactWhatsapp: "+265999445566",
    status: "Available",
    isApproved: true,
    isFeatured: true,
    viewCount: 87,
    createdAt: "2026-03-17",
    landlordName: "Jean-Pierre Mugisha",
    lat: -13.7883, lng: 33.9883,
  },
  {
    id: "15",
    title: "Student Bedsitter near Zomba Plateau",
    propertyType: "Bedsitter",
    bedrooms: 1,
    rentPrice: 40000,
    city: "Zomba",
    area: "Zomba Town",
    description: "Self-contained bedsitter near Zomba Plateau. Perfect for UNIMA students and lecturers. Walking distance to Chancellor College. Quiet environment for studying.",
    amenities: ["Water", "Electricity", "Flush Toilet", "Bathroom", "Kitchen"],
    images: [propertyBedsitter],
    contactPhone: "+265884556677",
    contactWhatsapp: "+265884556677",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 112,
    createdAt: "2026-03-14",
    landlordName: "Chikondi Mwanza",
    lat: -15.3733, lng: 35.3088,
  },
  {
    id: "16",
    title: "Student Room near LUANAR Bunda",
    propertyType: "Room",
    bedrooms: 1,
    rentPrice: 28000,
    city: "Lilongwe",
    area: "Bunda Campus",
    description: "Affordable room walking distance from LUANAR Bunda Campus. Many students in the area. Shared facilities. Landlord is helpful and student-friendly.",
    amenities: ["Water", "Electricity", "Pit Toilet", "Bathroom"],
    images: [propertyRoom],
    contactPhone: "+265991667788",
    contactWhatsapp: "+265991667788",
    status: "Available",
    isApproved: true,
    isFeatured: false,
    viewCount: 198,
    createdAt: "2026-03-15",
    landlordName: "Mr. Kambalame",
    lat: -14.1733, lng: 33.7688,
  },
];

export const formatPrice = (price: number): string => {
  return `MK ${price.toLocaleString()}`;
};

export const CITIES: string[] = ["Lilongwe", "Zomba", "Dzaleka"];
export const PROPERTY_TYPES: string[] = ["House", "Room", "Apartment", "Bedsitter", "Shop/Office"];
export const AMENITY_OPTIONS: string[] = ["Water", "Electricity", "Flush Toilet", "Pit Toilet", "Bathroom", "Kitchen", "Parking", "Wall Fence", "Tiled Floors"];
export const AMENITY_ICONS: Record<string, string> = {
  "Water": "💧",
  "Electricity": "⚡",
  "Flush Toilet": "🚽",
  "Pit Toilet": "🚽",
  "Bathroom": "🚿",
  "Kitchen": "🍳",
  "Parking": "🅿️",
  "Wall Fence": "🧱",
  "Tiled Floors": "🏠",
};
